{ TABLE stf1_main row size = 291 number of columns = 69 index size = 37 }
create table stf1_main 
  (
    fileid char(8),
    stusab char(2),
    sumlev smallint,
    geocomp smallint,
    chariter smallint,
    logrecnu integer,
    logrecpn smallint,
    partrec smallint,
    anrc char(2),
    aianace char(4),
    aianafp char(5),
    aianacc char(2),
    artli char(1),
    blck char(4),
    blckgr char(1),
    tractbna char(6),
    tract_blck char(6),
    congdis char(2),
    concitce char(1),
    concitfp char(5),
    concitcc char(2),
    concitsc char(2),
    cmsa char(2),
    cnty char(3),
    cntysc char(2),
    cousubce char(3),
    cousubfp char(5),
    cousubcc char(2),
    cousubsc char(2),
    divis char(1),
    extcitin char(1),
    intuc char(15),
    msacmsa char(4),
    msacmsas char(2),
    placece char(4),
    placefp char(5),
    placecc char(2),
    placedc char(1),
    placesc char(2),
    pmsa char(4),
    reg char(1),
    statece char(2),
    statefp char(2),
    urbanrur char(1),
    urbarea char(4),
    uasc char(2),
    sac1 char(5),
    sac2 char(5),
    sac3 char(4),
    sac4 char(4),
    sac5 char(3),
    sac6 char(3),
    sac7 char(2),
    sac8 char(2),
    sac9 char(1),
    sac10 char(1),
    arealand char(10),
    areawat char(10),
    anpsadpi char(66),
    funcstat char(1),
    gcuni char(1),
    hu100 char(1),
    intptlat char(9),
    intptlng char(10),
    partflag char(1),
    psadc char(2),
    pop100 integer,
    spflag char(1),
    tract_blckgr char(6)
  );
revoke all on stf1_main from "public";

create index i_mtractbna on stf1_main (tractbna);
create index ix139_15 on stf1_main (blckgr);
create unique index ix139_17 on stf1_main (tract_blck);



